name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to build release from"

jobs:
  build-ui:
    name: Build UI Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install UI dependencies
        run: yarn --cwd ui install

      - name: Build UI asset
        run: yarn --cwd ui build

      - name: GH Release
        uses: ncipollo/release-action@v1

        with:
          tags: ${{ github.event.inputs.tag }}
          artifacts: "ui/dist/extension.tar"
          token: ${{ secrets.GITHUB_TOKEN }}
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
